CREATE TABLE USERS(
    "ID" INT NOT NULL,
    "USERNAME" VARCHAR2(50) NOT NULL,
    "PASSWORD" VARCHAR2(50) NOT NULL,
    PRIMARY KEY("ID")
);

INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES (1,'admin','admin' );


INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES (3,'Piter','Piter' );